name: fifteen_min_schedule

on:
  schedule:
    - cron: '0/5 * * * *'
    - cron: '0/6 * * * *'

jobs:
  triggers:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - run: date && curl -sm 60 https://timeout.now.sh/20-